"""
RevAgent PDF Reporter — Professional Founder Exports
=====================================================
Generates high-end business reports from analysis JSON.
Uses fpdf2 for precise layout control.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from fpdf import FPDF

# Paths
ROOT = Path(__file__).resolve().parent.parent
PROCESSED_DIR = ROOT / "data" / "processed"
LATEST_REPORT_PATH = PROCESSED_DIR / "latest_report.json"
REPORTS_DIR = ROOT / "reports"

# Design Tokens (Premium Palette)
COLOR_PRIMARY = (26, 54, 93)     # Deep Blue
COLOR_SECONDARY = (43, 108, 176)  # Mid Blue
COLOR_ACCENT = (49, 151, 149)     # Teal
COLOR_TEXT = (45, 55, 72)        # Dark Gray
COLOR_GRAY = (113, 128, 150)      # Gray
COLOR_BG_LIGHT = (247, 250, 252)  # Light Gray


class RevAgentReport(FPDF):
    def header(self):
        # Logo text
        self.set_font("helvetica", "B", 16)
        self.set_text_color(*COLOR_PRIMARY)
        self.cell(0, 10, "RevAgent", border=0, ln=0, align="L")
        
        # Report Date
        self.set_font("helvetica", "", 10)
        self.set_text_color(*COLOR_GRAY)
        self.cell(0, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d')}", border=0, ln=1, align="R")
        
        # Horizontal line
        self.set_draw_color(*COLOR_PRIMARY)
        self.set_line_width(0.5)
        self.line(10, 22, 200, 22)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(*COLOR_GRAY)
        self.cell(0, 10, f"Page {self.page_no()} | Confidential Business Intelligence | Generated by RevAgent AI", 0, 0, "C")

    def section_title(self, title: str):
        self.set_font("helvetica", "B", 14)
        self.set_text_color(*COLOR_PRIMARY)
        self.cell(0, 10, title.upper(), ln=1)
        self.set_draw_color(*COLOR_ACCENT)
        self.set_line_width(0.3)
        self.line(self.get_x(), self.get_y(), self.get_x() + 20, self.get_y())
        self.ln(5)

    def write_summary(self, text: str):
        self.set_fill_color(*COLOR_BG_LIGHT)
        self.set_font("helvetica", "B", 12)
        self.set_text_color(*COLOR_TEXT)
        self.multi_cell(0, 10, text, border=0, fill=True, align="L")
        self.ln(5)

    def change_item(self, metric: str, direction: str, magnitude: str, period: str):
        self.set_font("helvetica", "B", 11)
        self.set_text_color(*COLOR_TEXT)
        self.cell(40, 8, f"{metric}:", ln=0)
        
        # Direction color
        if direction.lower() == "up":
            self.set_text_color(34, 153, 84) # Green
        else:
            self.set_text_color(192, 57, 43) # Red
            
        self.cell(20, 8, direction.upper(), ln=0)
        self.set_text_color(*COLOR_TEXT)
        self.cell(20, 8, magnitude, ln=0)
        
        self.set_font("helvetica", "I", 10)
        self.set_text_color(*COLOR_GRAY)
        self.cell(0, 8, f" ({period})", ln=1)

    def driver_item(self, hypothesis: str, confidence: str, evidence: str):
        self.set_font("helvetica", "B", 11)
        self.set_text_color(*COLOR_PRIMARY)
        conf_label = f"[{confidence.upper()}] "
        self.cell(0, 8, conf_label + hypothesis, ln=1)
        
        self.set_font("helvetica", "", 10)
        self.set_text_color(*COLOR_TEXT)
        self.multi_cell(0, 6, f"Evidence: {evidence}", ln=1)
        self.ln(2)

    def action_item(self, action: str, owner: str, urgency: str):
        self.set_font("helvetica", "B", 11)
        self.set_text_color(*COLOR_TEXT)
        urg_label = f"[{urgency.upper()}] "
        self.multi_cell(0, 8, urg_label + action, ln=1)
        
        self.set_font("helvetica", "I", 10)
        self.set_text_color(*COLOR_GRAY)
        self.cell(0, 6, f"Owner: {owner}", ln=1)
        self.ln(2)


def run_report() -> str:
    """
    Generate the PDF report.
    Returns the path to the generated file.
    """
    if not LATEST_REPORT_PATH.exists():
        raise FileNotFoundError("Analysis data not found. Run analysis first.")

    with open(LATEST_REPORT_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    mode = data.get("mode_used", "recent_issues")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_name = f"RevAgent_Report_{mode}_{timestamp}.pdf"
    output_path = REPORTS_DIR / report_name

    pdf = RevAgentReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 1. Summary
    report_type = data.get("report_type", "Executive Summary")
    pdf.section_title(report_type)
    pdf.write_summary(data.get("summary", "No summary available."))
    pdf.ln(5)

    # 2. Performance Shifts
    pdf.section_title("Performance Shifts")
    changes = data.get("changes", [])
    if not changes:
        pdf.set_font("helvetica", "I", 10)
        pdf.cell(0, 10, "No significant changes detected.", ln=1)
    else:
        for c in changes:
            pdf.change_item(
                c.get("metric", "Metric"),
                c.get("direction", "-"),
                c.get("magnitude", "-"),
                c.get("period", "recent")
            )
    pdf.ln(10)

    # 3. Causal Drivers
    pdf.section_title("Causal Analysis")
    drivers = data.get("drivers", [])
    if not drivers:
        pdf.set_font("helvetica", "I", 10)
        pdf.cell(0, 10, "No specific drivers identified.", ln=1)
    else:
        for d in drivers:
            pdf.driver_item(
                d.get("hypothesis", "Unknown factor"),
                d.get("confidence", "low"),
                d.get("evidence", "No evidence data.")
            )
    pdf.ln(10)

    # 4. Priority Actions
    pdf.section_title("Strategic Actions")
    actions = data.get("actions", [])
    if not actions:
        pdf.set_font("helvetica", "I", 10)
        pdf.cell(0, 10, "No immediate actions recommended.", ln=1)
    else:
        for a in actions:
            pdf.action_item(
                a.get("action", "General monitoring"),
                a.get("owner", "Founder"),
                a.get("urgency", "monitor")
            )
    pdf.ln(10)

    # 5. Watch List
    pdf.section_title("Watch List")
    watch = data.get("watch_list", [])
    if not watch:
        pdf.set_font("helvetica", "I", 10)
        pdf.cell(0, 10, "Nothing on the watch list.", ln=1)
    else:
        for w in watch:
            pdf.set_font("helvetica", "B", 11)
            pdf.set_text_color(*COLOR_TEXT)
            pdf.cell(40, 8, f"{w.get('metric')}:", ln=0)
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(*COLOR_GRAY)
            pdf.cell(0, 8, w.get("reason"), ln=1)

    pdf.output(str(output_path))
    print(f"Report generated: {output_path}")
    return str(output_path)


if __name__ == "__main__":
    try:
        run_report()
    except Exception as e:
        print(f"Error generating report: {e}")
